In [1]:
#import dependencies
import numpy as np
import pandas as pd
import time
import json
import matplotlib
from pprint import pprint

In [2]:
#load the raw data file retrieved from MTA website
#convert to pandas dataframe

df = pd.read_csv('turnstile_170624.txt')
new_header = []
for col in df.columns:
    col=col.strip()
    new_header.append(col)
df.columns = new_header
df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES', 'EXITS'],
      dtype='object')

In [3]:
df.head(20)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/17/2017,00:00:00,REGULAR,6224816,2107317
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/17/2017,04:00:00,REGULAR,6224850,2107322
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/17/2017,08:00:00,REGULAR,6224885,2107352
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/17/2017,12:00:00,REGULAR,6225005,2107452
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/17/2017,16:00:00,REGULAR,6225248,2107513
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/17/2017,20:00:00,REGULAR,6225548,2107565
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/18/2017,00:00:00,REGULAR,6225716,2107586
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/18/2017,04:00:00,REGULAR,6225741,2107590
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/18/2017,08:00:00,REGULAR,6225762,2107607
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/18/2017,12:00:00,REGULAR,6225879,2107676
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/18/2017,16:00:00,REGULAR,6226063,2107714
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/18/2017,20:00:00,REGULAR,6226295,2107755
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/19/2017,00:00:00,REGULAR,6226407,2107778
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/19/2017,04:00:00,REGULAR,6226413,2107779
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/19/2017,08:00:00,REGULAR,6226460,2107870
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/19/2017,12:00:00,REGULAR,6226625,2108117
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/19/2017,16:00:00,REGULAR,6226906,2108190
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/19/2017,20:00:00,REGULAR,6227611,2108288
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2017,00:00:00,REGULAR,6227770,2108316
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2017,04:00:00,REGULAR,6227785,2108321

In [4]:
df.info

<bound method DataFrame.info of           C/A  UNIT       SCP        STATION LINENAME DIVISION        DATE  \
0        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/17/2017
1        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/17/2017
2        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/17/2017
3        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/17/2017
4        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/17/2017
5        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/17/2017
6        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/18/2017
7        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/18/2017
8        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/18/2017
9        A002  R051  02-00-00          59 ST  NQR456W      BMT  06/18/2017
10       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/18/2017
11       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/18/2017
12       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/19/2017
13       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/19/2017
14       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/19/2017
15       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/19/2017
16       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/19/2017
17       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/19/2017
18       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/20/2017
19       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/20/2017
20       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/20/2017
21       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/20/2017
22       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/20/2017
23       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/20/2017
24       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/21/2017
25       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/21/2017
26       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/21/2017
27       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/21/2017
28       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/21/2017
29       A002  R051  02-00-00          59 ST  NQR456W      BMT  06/21/2017
...       ...   ...       ...            ...      ...      ...         ...
197386  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/19/2017
197387  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/19/2017
197388  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/19/2017
197389  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/19/2017
197390  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/19/2017
197391  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/19/2017
197392  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/20/2017
197393  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/20/2017
197394  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/20/2017
197395  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/20/2017
197396  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/20/2017
197397  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/20/2017
197398  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/21/2017
197399  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/21/2017
197400  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/21/2017
197401  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/21/2017
197402  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/21/2017
197403  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/21/2017
197404  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/22/2017
197405  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/22/2017
197406  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/22/2017
197407  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/22/2017
197408  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/22/2017
197409  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/22/2017
197410  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/23/2017
197411  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/23/2017
197412  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/23/2017
197413  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/23/2017
197414  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/23/2017
197415  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/23/2017

            TIME     DESC  ENTRIES    EXITS
0       00:00:00  REGULAR  6224816  2107317
1       04:00:00  REGULAR  6224850  2107322
2       08:00:00  REGULAR  6224885  2107352
3       12:00:00  REGULAR  6225005  2107452
4       16:00:00  REGULAR  6225248  2107513
5       20:00:00  REGULAR  6225548  2107565
6       00:00:00  REGULAR  6225716  2107586
7       04:00:00  REGULAR  6225741  2107590
8       08:00:00  REGULAR  6225762  2107607
9       12:00:00  REGULAR  6225879  2107676
10      16:00:00  REGULAR  6226063  2107714
11      20:00:00  REGULAR  6226295  2107755
12      00:00:00  REGULAR  6226407  2107778
13      04:00:00  REGULAR  6226413  2107779
14      08:00:00  REGULAR  6226460  2107870
15      12:00:00  REGULAR  6226625  2108117
16      16:00:00  REGULAR  6226906  2108190
17      20:00:00  REGULAR  6227611  2108288
18      00:00:00  REGULAR  6227770  2108316
19      04:00:00  REGULAR  6227785  2108321
20      08:00:00  REGULAR  6227837  2108448
21      12:00:00  REGULAR  6228001  2108732
22      16:00:00  REGULAR  6228295  2108798
23      20:00:00  REGULAR  6229118  2108869
24      00:00:00  REGULAR  6229332  2108905
25      04:00:00  REGULAR  6229347  2108906
26      08:00:00  REGULAR  6229394  2109010
27      12:00:00  REGULAR  6229553  2109269
28      16:00:00  REGULAR  6229829  2109341
29      20:00:00  REGULAR  6230582  2109401
...          ...      ...      ...      ...
197386  01:00:00  REGULAR     5554      301
197387  05:00:00  REGULAR     5554      301
197388  09:00:00  REGULAR     5554      301
197389  13:00:00  REGULAR     5554      301
197390  17:00:00  REGULAR     5554      301
197391  21:00:00  REGULAR     5554      301
197392  01:00:00  REGULAR     5554      301
197393  05:00:00  REGULAR     5554      301
197394  09:00:00  REGULAR     5554      301
197395  13:00:00  REGULAR     5554      301
197396  17:00:00  REGULAR     5554      301
197397  21:00:00  REGULAR     5554      301
197398  01:00:00  REGULAR     5554      301
197399  05:00:00  REGULAR     5554      301
197400  09:00:00  REGULAR     5554      301
197401  13:00:00  REGULAR     5554      301
197402  17:00:00  REGULAR     5554      301
197403  21:00:00  REGULAR     5554      301
197404  01:00:00  REGULAR     5554      301
197405  05:00:00  REGULAR     5554      301
197406  09:00:00  REGULAR     5554      301
197407  13:00:00  REGULAR     5554      301
197408  17:00:00  REGULAR     5554      301
197409  21:00:00  REGULAR     5554      301
197410  01:00:00  REGULAR     5554      301
197411  05:00:00  REGULAR     5554      301
197412  09:00:00  REGULAR     5554      301
197413  13:00:00  REGULAR     5554      301
197414  17:00:00  REGULAR     5554      301
197415  21:00:00  REGULAR     5554      301

[197416 rows x 11 columns]>

In [5]:
#Division is not neccesary for this analysis 
#archaic info pre 1940's
df.drop(df.columns[[5]], axis=1, inplace=True)
df.head(20)

,C/A,UNIT,SCP,STATION,LINENAME,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,06/17/2017,00:00:00,REGULAR,6224816,2107317
1,A002,R051,02-00-00,59 ST,NQR456W,06/17/2017,04:00:00,REGULAR,6224850,2107322
2,A002,R051,02-00-00,59 ST,NQR456W,06/17/2017,08:00:00,REGULAR,6224885,2107352
3,A002,R051,02-00-00,59 ST,NQR456W,06/17/2017,12:00:00,REGULAR,6225005,2107452
4,A002,R051,02-00-00,59 ST,NQR456W,06/17/2017,16:00:00,REGULAR,6225248,2107513
5,A002,R051,02-00-00,59 ST,NQR456W,06/17/2017,20:00:00,REGULAR,6225548,2107565
6,A002,R051,02-00-00,59 ST,NQR456W,06/18/2017,00:00:00,REGULAR,6225716,2107586
7,A002,R051,02-00-00,59 ST,NQR456W,06/18/2017,04:00:00,REGULAR,6225741,2107590
8,A002,R051,02-00-00,59 ST,NQR456W,06/18/2017,08:00:00,REGULAR,6225762,2107607
9,A002,R051,02-00-00,59 ST,NQR456W,06/18/2017,12:00:00,REGULAR,6225879,2107676
10,A002,R051,02-00-00,59 ST,NQR456W,06/18/2017,16:00:00,REGULAR,6226063,2107714
11,A002,R051,02-00-00,59 ST,NQR456W,06/18/2017,20:00:00,REGULAR,6226295,2107755
12,A002,R051,02-00-00,59 ST,NQR456W,06/19/2017,00:00:00,REGULAR,6226407,2107778
13,A002,R051,02-00-00,59 ST,NQR456W,06/19/2017,04:00:00,REGULAR,6226413,2107779
14,A002,R051,02-00-00,59 ST,NQR456W,06/19/2017,08:00:00,REGULAR,6226460,2107870
15,A002,R051,02-00-00,59 ST,NQR456W,06/19/2017,12:00:00,REGULAR,6226625,2108117
16,A002,R051,02-00-00,59 ST,NQR456W,06/19/2017,16:00:00,REGULAR,6226906,2108190
17,A002,R051,02-00-00,59 ST,NQR456W,06/19/2017,20:00:00,REGULAR,6227611,2108288
18,A002,R051,02-00-00,59 ST,NQR456W,06/20/2017,00:00:00,REGULAR,6227770,2108316
19,A002,R051,02-00-00,59 ST,NQR456W,06/20/2017,04:00:00,REGULAR,6227785,2108321

In [6]:
#Convert columsn date and time to a single timedate column
df['DATETIME'] = pd.to_datetime(df['DATE'] + ' ' + df['TIME'], format = '%m/%d/%Y %H:%M:%S')
df.head(20)
df.drop('DATE', axis=1, inplace=True)

In [7]:
df.drop('TIME', axis=1, inplace=True)
df.head(20)

,C/A,UNIT,SCP,STATION,LINENAME,DESC,ENTRIES,EXITS,DATETIME
0,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6224816,2107317,2017-06-17 00:00:00
1,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6224850,2107322,2017-06-17 04:00:00
2,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6224885,2107352,2017-06-17 08:00:00
3,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225005,2107452,2017-06-17 12:00:00
4,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225248,2107513,2017-06-17 16:00:00
5,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225548,2107565,2017-06-17 20:00:00
6,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225716,2107586,2017-06-18 00:00:00
7,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225741,2107590,2017-06-18 04:00:00
8,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225762,2107607,2017-06-18 08:00:00
9,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225879,2107676,2017-06-18 12:00:00
10,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226063,2107714,2017-06-18 16:00:00
11,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226295,2107755,2017-06-18 20:00:00
12,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226407,2107778,2017-06-19 00:00:00
13,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226413,2107779,2017-06-19 04:00:00
14,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226460,2107870,2017-06-19 08:00:00
15,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226625,2108117,2017-06-19 12:00:00
16,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226906,2108190,2017-06-19 16:00:00
17,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227611,2108288,2017-06-19 20:00:00
18,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227770,2108316,2017-06-20 00:00:00
19,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227785,2108321,2017-06-20 04:00:00

In [8]:
df.drop('EXITS', axis=1, inplace=True)

In [9]:
df.head(50)

,C/A,UNIT,SCP,STATION,LINENAME,DESC,ENTRIES,DATETIME
0,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6224816,2017-06-17 00:00:00
1,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6224850,2017-06-17 04:00:00
2,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6224885,2017-06-17 08:00:00
3,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225005,2017-06-17 12:00:00
4,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225248,2017-06-17 16:00:00
5,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225548,2017-06-17 20:00:00
6,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225716,2017-06-18 00:00:00
7,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225741,2017-06-18 04:00:00
8,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225762,2017-06-18 08:00:00
9,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6225879,2017-06-18 12:00:00
10,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226063,2017-06-18 16:00:00
11,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226295,2017-06-18 20:00:00
12,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226407,2017-06-19 00:00:00
13,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226413,2017-06-19 04:00:00
14,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226460,2017-06-19 08:00:00
15,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226625,2017-06-19 12:00:00
16,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6226906,2017-06-19 16:00:00
17,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227611,2017-06-19 20:00:00
18,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227770,2017-06-20 00:00:00
19,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227785,2017-06-20 04:00:00
20,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6227837,2017-06-20 08:00:00
21,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6228001,2017-06-20 12:00:00
22,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6228295,2017-06-20 16:00:00
23,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6229118,2017-06-20 20:00:00
24,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6229332,2017-06-21 00:00:00
25,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6229347,2017-06-21 04:00:00
26,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6229394,2017-06-21 08:00:00
27,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6229553,2017-06-21 12:00:00
28,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6229829,2017-06-21 16:00:00
29,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6230582,2017-06-21 20:00:00
30,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6230793,2017-06-22 00:00:00
31,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6230811,2017-06-22 04:00:00
32,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6230853,2017-06-22 08:00:00
33,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6230992,2017-06-22 12:00:00
34,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6231237,2017-06-22 16:00:00
35,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6231957,2017-06-22 20:00:00
36,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6232184,2017-06-23 00:00:00
37,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6232214,2017-06-23 04:00:00
38,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6232261,2017-06-23 08:00:00
39,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6232419,2017-06-23 12:00:00
40,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6232792,2017-06-23 16:00:00
41,A002,R051,02-00-00,59 ST,NQR456W,REGULAR,6233500,2017-06-23 20:00:00
42,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5621478,2017-06-17 00:00:00
43,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5621501,2017-06-17 04:00:00
44,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5621519,2017-06-17 08:00:00
45,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5621643,2017-06-17 12:00:00
46,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5621888,2017-06-17 16:00:00
47,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5622148,2017-06-17 20:00:00
48,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5622284,2017-06-18 00:00:00
49,A002,R051,02-00-01,59 ST,NQR456W,REGULAR,5622302,2017-06-18 04:00:00

In [10]:
df.describe

<bound method NDFrame.describe of           C/A  UNIT       SCP        STATION LINENAME     DESC  ENTRIES  \
0        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6224816
1        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6224850
2        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6224885
3        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225005
4        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225248
5        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225548
6        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225716
7        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225741
8        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225762
9        A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6225879
10       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226063
11       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226295
12       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226407
13       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226413
14       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226460
15       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226625
16       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6226906
17       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6227611
18       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6227770
19       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6227785
20       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6227837
21       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6228001
22       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6228295
23       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6229118
24       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6229332
25       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6229347
26       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6229394
27       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6229553
28       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6229829
29       A002  R051  02-00-00          59 ST  NQR456W  REGULAR  6230582
...       ...   ...       ...            ...      ...      ...      ...
197386  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197387  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197388  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197389  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197390  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197391  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197392  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197393  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197394  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197395  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197396  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197397  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197398  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197399  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197400  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197401  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197402  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197403  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197404  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197405  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197406  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197407  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197408  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197409  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197410  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197411  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197412  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197413  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197414  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554
197415  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R  REGULAR     5554

                  DATETIME
0      2017-06-17 00:00:00
1      2017-06-17 04:00:00
2      2017-06-17 08:00:00
3      2017-06-17 12:00:00
4      2017-06-17 16:00:00
5      2017-06-17 20:00:00
6      2017-06-18 00:00:00
7      2017-06-18 04:00:00
8      2017-06-18 08:00:00
9      2017-06-18 12:00:00
10     2017-06-18 16:00:00
11     2017-06-18 20:00:00
12     2017-06-19 00:00:00
13     2017-06-19 04:00:00
14     2017-06-19 08:00:00
15     2017-06-19 12:00:00
16     2017-06-19 16:00:00
17     2017-06-19 20:00:00
18     2017-06-20 00:00:00
19     2017-06-20 04:00:00
20     2017-06-20 08:00:00
21     2017-06-20 12:00:00
22     2017-06-20 16:00:00
23     2017-06-20 20:00:00
24     2017-06-21 00:00:00
25     2017-06-21 04:00:00
26     2017-06-21 08:00:00
27     2017-06-21 12:00:00
28     2017-06-21 16:00:00
29     2017-06-21 20:00:00
...                    ...
197386 2017-06-19 01:00:00
197387 2017-06-19 05:00:00
197388 2017-06-19 09:00:00
197389 2017-06-19 13:00:00
197390 2017-06-19 17:00:00
197391 2017-06-19 21:00:00
197392 2017-06-20 01:00:00
197393 2017-06-20 05:00:00
197394 2017-06-20 09:00:00
197395 2017-06-20 13:00:00
197396 2017-06-20 17:00:00
197397 2017-06-20 21:00:00
197398 2017-06-21 01:00:00
197399 2017-06-21 05:00:00
197400 2017-06-21 09:00:00
197401 2017-06-21 13:00:00
197402 2017-06-21 17:00:00
197403 2017-06-21 21:00:00
197404 2017-06-22 01:00:00
197405 2017-06-22 05:00:00
197406 2017-06-22 09:00:00
197407 2017-06-22 13:00:00
197408 2017-06-22 17:00:00
197409 2017-06-22 21:00:00
197410 2017-06-23 01:00:00
197411 2017-06-23 05:00:00
197412 2017-06-23 09:00:00
197413 2017-06-23 13:00:00
197414 2017-06-23 17:00:00
197415 2017-06-23 21:00:00

[197416 rows x 8 columns]>

In [14]:
df['ENTRIES'].describe()

count    1.974160e+05
mean     3.887172e+07
std      2.067859e+08
min      0.000000e+00
25%      4.880605e+05
50%      2.652587e+06
75%      6.788725e+06
max      2.130434e+09
Name: ENTRIES, dtype: float64